---
- name: (Debian) Bind Apache to specified HTTP port
  ansible.builtin.lineinfile:
    path: "{{ apache_config_ports }}"
    regexp: "^Listen 80$"
    line: "Listen {{ apache_port_http }}"
  when: ansible_os_family|lower == "debian"

- name: (Debian) Bind Apache to specified HTTPS port
  ansible.builtin.replace:
    path: "{{ apache_config_ports }}"
    regexp: "Listen 443$"
    replace: "Listen {{ apache_port_https }}"
  when: ansible_os_family|lower == "debian"

- name: (Debian) Remove default virtualhost
  ansible.builtin.file:
    path: "{{ apache_config_site_path }}/000-default.conf"
    state: absent
  when: ansible_os_family|lower == "debian"

- name: (Debian) Enable Apache modules
  community.general.apache2_module:
    name: "{{ item }}"
    state: present
    ignore_configcheck: true
  failed_when:
    - apache_modules.rc is defined
    - apache_modules.rc > 0
  notify: Restart apache
  register: apache_modules
  when: ansible_os_family|lower == "debian"
  with_items:
    - proxy_fcgi
    - rewrite
    - ssl
