---
- name: (Debian) Install required repo management packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg
      - software-properties-common
      - gpg-agent
    cache_valid_time: "3600"
    force_apt_get: true
    state: present
    update_cache: true

- name: (Debian) Add official NGINX repo signing key
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: (Debian) Add official NGINX repo
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} nginx"
    state: present

- name: (Debian) Update APT cache
  ansible.builtin.apt:
    force_apt_get: true
    cache_valid_time: "3600"
    state: present
    update_cache: true

- name: (Debian) Create nginx group
  ansible.builtin.group:
    name: "{{ nginx_group }}"
    state: present

- name: (Debian) Create nginx user
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    state: present
    create_home: false
    groups:
      - nobody

- name: (Debian) Silently stop Apache if running
  ansible.builtin.service:
    name: "{{ apache_daemon | default('apache2') }}"
    state: stopped
  changed_when: false
  failed_when: false
