---
- name: Exercice 8 - Installation MySQL
  hosts: db_servers
  tasks:
    - name: Installer MySQL Server
      apt:
        name: mysql-server
        state: latest
        update_cache: true
    - name: redémarrer mysql
      service:
        name: mysql
        state: restarted
